server:
  shutdown: graceful

jwt:
  secret-key: fadsdnfiew232938rfksl#$@#dsfsdnf
  issuer: han
  expired-time: 180000000000 # 3000h #개발용이어서 길게 줌

board:
  file:
    upload-path: upload-file

# swaggerdoc
springdoc:
  version: v1.0.0
  packages-to-scan: org.example.han
  swagger-ui:
    enabled: true
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups.enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

spring:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/board-db
    username: sa
    password:
#  jackson:
#    default-property-inclusion: non_null
  jpa:
    database: h2
    show-sql: true
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        query:
          in_clause_parameter_padding: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: -1 # 업로드 파일 용량 제한 없음
      max-request-size: -1 # 업로드 파일 용량 제한 없음
