# swaggerdoc
springdoc:
  version: v1.0.0
  packages-to-scan: org.example.han
  swagger-ui:
    enabled: false
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups.enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

