create table "boards" (
    "create_user_id" bigint,
    "created_at" timestamp(6) with time zone,
    "id" bigint generated by default as identity,
    "update_user_id" bigint,
    "updated_at" timestamp(6) with time zone,
    "content" varchar(255),
    "title" varchar(255),
    primary key ("id")
)
create table "comments" (
    "board_id" bigint,
    "create_user_id" bigint,
    "created_at" timestamp(6) with time zone,
    "id" bigint generated by default as identity,
    "updated_at" timestamp(6) with time zone,
    "comment" varchar(255),
    primary key ("id")
)
create table "users" (
    "created_at" timestamp(6) with time zone,
    "id" bigint generated by default as identity,
    "updated_at" timestamp(6) with time zone,
    "base64encoded_string" varchar(255),
    "encoded_password" varchar(255),
    "login_id" varchar(255),
    "name" varchar(255),
    primary key ("id")
)

create table "upload-files" (
    "create_user_id" bigint,
    "created_at" timestamp(6) with time zone,
    "id" bigint generated by default as identity,
    "updated_at" timestamp(6) with time zone,
    "file_name" varchar(255),
    "file_path" varchar(255),
    primary key ("id")
)