-- 필요시 테이블 삭제
-- 서버 실행 시 자동으로 생성된 테이블이라면 삭제 시 아래 순서를 꼭 지켜서 삭제한다
-- 자동으로 제약조건이 걸어주기 때문
drop table "upload-files";
drop table "comments";
drop table "boards";
drop table "users";

-- 테이블 생성
create table "boards" (
    "create_user_id" bigint,
    "created_at" timestamp(6) with time zone,
    "id" bigint generated by default as identity,
    "update_user_id" bigint,
    "updated_at" timestamp(6) with time zone,
    "content" varchar(255),
    "title" varchar(255),
    primary key ("id")
)
create table "comments" (
    "board_id" bigint,
    "create_user_id" bigint,
    "created_at" timestamp(6) with time zone,
    "id" bigint generated by default as identity,
    "updated_at" timestamp(6) with time zone,
    "comment" varchar(255),
    primary key ("id")
)
create table "users" (
    "created_at" timestamp(6) with time zone,
    "id" bigint generated by default as identity,
    "updated_at" timestamp(6) with time zone,
    "extra_user_info" clob,
    "profile_file_path" varchar(255),
    "encoded_password" varchar(255),
    "login_id" varchar(255),
    "name" varchar(255),
    primary key ("id")
)

create table "upload-files" (
    "create_user_id" bigint,
    "created_at" timestamp(6) with time zone,
    "id" bigint generated by default as identity,
    "updated_at" timestamp(6) with time zone,
    "file_name" varchar(255),
    "file_path" varchar(255),
    primary key ("id")
)